### ISSUE TITLE
大佬你好，请问设置输入框的高度后输入文字对不齐怎么办

### ISSUE THREAD

**Issue by mdddj** [Fliggy-Mobile/fsearch#2]
![image](https://user-images.githubusercontent.com/29020213/86425472-de517800-bd17-11ea-9fdf-7c93f1337efd.png)

设置高一点就没事

**Comment by shaohui93** [comment]
我也是这样 设置成30  光标就偏下 设置成50 就居中了，这个问题你解决了吗

**Comment by mdddj** [comment]
> 我也是这样 设置成30 光标就偏下 设置成50 就居中了，这个问题你解决了吗

没有解决,我换成自带的TextField了

**Comment by chenBingX** [comment]
这个问题已经在 `1.0.1` 版本中得到适配。
欢迎继续对 FWidget 保持关注。
