### ISSUE TITLE
请问光标和输入的rearing会往下偏移是咋回事呀！

### ISSUE THREAD

**Issue by shaohui93** [Fliggy-Mobile/fsearch#3]
这个是我的代码
 FSearch(
                controller: controller,
                height: 30,
                backgroundColor: Colours.bg_gray,
                corner: FSearchCorner.all(14),
                style: TextStyle(fontSize: 12.0, color: Colors.black),
                margin: EdgeInsets.only(left: 12.0, right: 12.0),
                hints: ["", ""],
                hintStyle: TextStyle(fontSize: 12.0, color: Colors.black),
                prefixes: [
                  const SizedBox(width: 15.0),
                  Icon(
                    Icons.search,
                    size: 18,
                    color: Colours.text_tab_black,
                  ),
                  const SizedBox(width: 3.0)
                ],
                onSearch: (value) {
                  setState(() {});
                },
              ),

![image](https://user-images.githubusercontent.com/24472038/88249797-1c6b0780-ccd8-11ea-86e3-bc2f8d6dc953.png)

**Comment by chenBingX** [comment]
这个问题已经在 `1.0.1` 版本中得到适配。
欢迎继续对 FWidget 保持关注。
